trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'msal-angular (build)'
    trigger: true

jobs:
- deployment: publish
  displayName: 'publish'
  environment: 'production'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: npmAuthenticate@0
          displayName: 'authenticate with npm'
          enabled: true
          inputs:
            customEndpoint: 'npm - official'
            workingFile: '$(Pipeline.Workspace)/build/drop/byteterrace/msal-angular/.npmrc'
        - task: CmdLine@2
          displayName: 'publish npm package'
          enabled: true
          inputs:
            script: 'npm publish --access public'
            workingDirectory: '$(Pipeline.Workspace)/build/drop/byteterrace/msal-angular'
  workspace:
    clean: all
